<?php

namespace Database\Seeders;

use App\Models\ActivityLog;
use App\Models\Business;
use App\Models\User;
use Carbon\Carbon;
use Illuminate\Database\Seeder;

class ActivityLogSeeder extends Seeder
{
    public function run(): void
    {
        $business = Business::withoutGlobalScopes()->where('subdomain', 'salone')->first();
        $admin    = User::where('email', 'admin@rossini.test')->first();
        $staff    = User::where('email', 'marco@rossini.test')->first();
        $customer = User::where('email', 'giovanni@rossini.test')->first();

        $logs = [
            // Model events (activity)
            [
                'business_id' => $business?->id,
                'log_name'    => 'activity',
                'description' => 'Appuntamento creato',
                'event'       => 'created',
                'type'        => 'activity',
                'level'       => 'info',
                'source'      => 'model_event',
                'causer_type' => $admin ? User::class : null,
                'causer_id'   => $admin?->id,
                'url'         => '/admin/appointments/create',
                'method'      => 'POST',
                'ip_address'  => '192.168.1.10',
                'created_at'  => now()->subHours(1),
            ],
            [
                'business_id' => $business?->id,
                'log_name'    => 'activity',
                'description' => 'Appuntamento aggiornato: status pending → confirmed',
                'event'       => 'updated',
                'type'        => 'activity',
                'level'       => 'info',
                'source'      => 'model_event',
                'causer_type' => $admin ? User::class : null,
                'causer_id'   => $admin?->id,
                'url'         => '/admin/appointments/1',
                'method'      => 'PATCH',
                'ip_address'  => '192.168.1.10',
                'created_at'  => now()->subHours(2),
            ],
            [
                'business_id' => $business?->id,
                'log_name'    => 'activity',
                'description' => 'Pagamento completato: €28.00',
                'event'       => 'updated',
                'type'        => 'activity',
                'level'       => 'info',
                'source'      => 'model_event',
                'causer_type' => $customer ? User::class : null,
                'causer_id'   => $customer?->id,
                'url'         => '/booking/payment/callback',
                'method'      => 'GET',
                'ip_address'  => '5.90.32.14',
                'created_at'  => now()->subHours(3),
            ],
            [
                'business_id' => $business?->id,
                'log_name'    => 'activity',
                'description' => 'Servizio "Taglio + Barba" modificato: prezzo 25.00 → 28.00',
                'event'       => 'updated',
                'type'        => 'activity',
                'level'       => 'info',
                'source'      => 'model_event',
                'causer_type' => $admin ? User::class : null,
                'causer_id'   => $admin?->id,
                'url'         => '/admin/services/2',
                'method'      => 'PATCH',
                'ip_address'  => '192.168.1.10',
                'created_at'  => now()->subDays(1),
            ],
            [
                'business_id' => $business?->id,
                'log_name'    => 'activity',
                'description' => 'Nuovo cliente registrato: Giovanni Esposito',
                'event'       => 'created',
                'type'        => 'activity',
                'level'       => 'info',
                'source'      => 'model_event',
                'causer_type' => null,
                'causer_id'   => null,
                'url'         => '/register',
                'method'      => 'POST',
                'ip_address'  => '185.201.10.44',
                'created_at'  => now()->subDays(2),
            ],

            // Exception / errors
            [
                'business_id' => $business?->id,
                'log_name'    => 'exception',
                'description' => 'Stripe webhook signature mismatch: invalid signature',
                'event'       => null,
                'type'        => 'error',
                'level'       => 'error',
                'source'      => 'exception_reporter',
                'causer_type' => null,
                'causer_id'   => null,
                'url'         => '/webhooks/stripe',
                'method'      => 'POST',
                'ip_address'  => '3.18.12.63',
                'created_at'  => now()->subMinutes(30),
            ],
            [
                'business_id' => $business?->id,
                'log_name'    => 'exception',
                'description' => 'Twilio: impossibile inviare SMS a +39 333 1234567 — codice 21211',
                'event'       => null,
                'type'        => 'error',
                'level'       => 'warning',
                'source'      => 'exception_reporter',
                'causer_type' => null,
                'causer_id'   => null,
                'url'         => null,
                'method'      => null,
                'ip_address'  => null,
                'created_at'  => now()->subHours(5),
            ],
            [
                'business_id' => null,
                'log_name'    => 'exception',
                'description' => 'QueryException: SQLSTATE[42S22] Column not found: 1054 Unknown column \'business_id\'',
                'event'       => null,
                'type'        => 'error',
                'level'       => 'critical',
                'source'      => 'exception_reporter',
                'causer_type' => $admin ? User::class : null,
                'causer_id'   => $admin?->id,
                'url'         => '/admin/reports',
                'method'      => 'GET',
                'ip_address'  => '192.168.1.10',
                'created_at'  => now()->subDays(3),
            ],
            [
                'business_id' => $business?->id,
                'log_name'    => 'exception',
                'description' => 'ModelNotFoundException: Appointment #999 non trovato',
                'event'       => null,
                'type'        => 'error',
                'level'       => 'error',
                'source'      => 'exception_reporter',
                'causer_type' => $staff ? User::class : null,
                'causer_id'   => $staff?->id,
                'url'         => '/admin/appointments/999',
                'method'      => 'GET',
                'ip_address'  => '10.0.0.5',
                'created_at'  => now()->subDays(1)->subHours(2),
            ],

            // System events
            [
                'business_id' => null,
                'log_name'    => 'system',
                'description' => 'activity_log:clean completato — 0 record rimossi',
                'event'       => null,
                'type'        => 'system',
                'level'       => 'info',
                'source'      => 'manual',
                'causer_type' => null,
                'causer_id'   => null,
                'url'         => null,
                'method'      => null,
                'ip_address'  => null,
                'created_at'  => now()->subHours(6),
            ],
            [
                'business_id' => null,
                'log_name'    => 'system',
                'description' => 'Queue worker riavviato dopo deploy',
                'event'       => null,
                'type'        => 'system',
                'level'       => 'info',
                'source'      => 'manual',
                'causer_type' => null,
                'causer_id'   => null,
                'url'         => null,
                'method'      => null,
                'ip_address'  => null,
                'created_at'  => now()->subDays(4),
            ],
            [
                'business_id' => null,
                'log_name'    => 'system',
                'description' => 'Backup database completato con successo (142 MB)',
                'event'       => null,
                'type'        => 'system',
                'level'       => 'info',
                'source'      => 'manual',
                'causer_type' => null,
                'causer_id'   => null,
                'url'         => null,
                'method'      => null,
                'ip_address'  => null,
                'created_at'  => now()->subDays(1)->subHours(8),
            ],
            [
                'business_id' => null,
                'log_name'    => 'system',
                'description' => 'Rate limit superato: 120 req/min da IP 91.188.42.11',
                'event'       => null,
                'type'        => 'system',
                'level'       => 'warning',
                'source'      => 'manual',
                'causer_type' => null,
                'causer_id'   => null,
                'url'         => '/api/v1/slots',
                'method'      => 'GET',
                'ip_address'  => '91.188.42.11',
                'created_at'  => now()->subHours(4),
            ],

            // Webhook events
            [
                'business_id' => $business?->id,
                'log_name'    => 'webhook',
                'description' => 'Stripe payment_intent.succeeded ricevuto: pi_3abc123',
                'event'       => null,
                'type'        => 'activity',
                'level'       => 'info',
                'source'      => 'webhook',
                'causer_type' => null,
                'causer_id'   => null,
                'url'         => '/webhooks/stripe',
                'method'      => 'POST',
                'ip_address'  => '3.18.12.63',
                'created_at'  => now()->subHours(3)->subMinutes(20),
            ],
            [
                'business_id' => $business?->id,
                'log_name'    => 'webhook',
                'description' => 'Stripe payment_intent.payment_failed: carte rifiutata (insufficient_funds)',
                'event'       => null,
                'type'        => 'error',
                'level'       => 'warning',
                'source'      => 'webhook',
                'causer_type' => null,
                'causer_id'   => null,
                'url'         => '/webhooks/stripe',
                'method'      => 'POST',
                'ip_address'  => '3.18.12.63',
                'created_at'  => now()->subDays(2)->subHours(1),
            ],
        ];

        foreach ($logs as $log) {
            ActivityLog::create($log);
        }
    }
}
